### PR TITLE
Feat: Download Solution Button

### PR DESCRIPTION
**Pull request by Bouncey**

### CODE REVIEW

**Comment by nikrb** [comment]
@Bouncey haha sorry just followed suit from freecodecamp. I can merge this with master if you can just confirm that is what is required :)

**Comment by Bouncey** [comment]
What you will need to do to resolve the conflicts is

`git pull --rebase upstream master`

`git` will then tell you where the conflicts are, if you use VS Code, then they have a nice feature to help resolve  conflicts.

Good luck :+1:

**Comment by nikrb** [comment]
@Bouncey hmmm, no conflicts, but 67 commits ahead of `enh/download-solution`. Suspect I messed up. Should I push and see what happens?
I only changed the one file, `src/templates/Challenges/components/CompletionModal.js`. I could just reclone and create new branch off `master` and apply the change?
What do you think? Sorry for the hassle.

**Comment by Bouncey** [comment]
No no, just `git push origin enh/download-solution` and everything should be fine

**Comment by Bouncey** [comment]
@nikrb how are you getting on with this?

I am available to help you in any way I can.

**Comment by nikrb** [comment]
@Bouncey oh sorry dude, I pushed the branch, merged with master a week ago `Merge branch 'master' into enh/download-solution - 02e7c8f `, see above.
Apologies if we're not there yet, I was under the impression we were good to go after the merge with master.

**Comment by Bouncey** [comment]
Great work @nikrb :+1: Thanks

**Pull request merged**
