### PR TITLE
Change editor theme

### LINKED ISSUE #89: Monaco Editor should use the light mode in the light version of the learn app.
The theme to be used on the monaco editor should be light one on the light version of learn

### PR DESCRIPTION
**Pull request by huyenltnguyen**
Changed editor theme from `vs-dark` to `vs`.
But please tell me there'll be dark mode or I'll learn from a fork!

~Threat~ Joke aside, thank you for making it way easier to setup and contribute to 👏 

Closes #89

### CODE REVIEW

**Comment by raisedadead** [comment]
@huyenltnguyen yes, of course.. as you may have noticed that this an overhaul of what we had. We have split up the repos and things are moving smooth.

The UX needs some work. We know and are pushing that gradually, and we need all the help we can. Thanks for the PR.

We will get that dark mode, soon.. just getting the main functionality ready first.

**Comment by huyenltnguyen** [comment]
@raisedadead I totally understand that. I'm somehow late for the party, just learned about this repo like a few days ago. I appreciate all the work you guys have been doing, and yes, I'll definitely try to help as much as I can. 
Thanks for the merge and happy coding! 😄

**Comment by Bouncey** [comment]
@huyenltnguyen, I really liked the dark theme for the editor, I will try to sneak this into a feature list, near the top.

**Comment by huyenltnguyen** [comment]
@Bouncey Thank you for all the work, and for offering a fix! Hope you didn't take my joke so seriously, theme/mode is never a deal breaker for me 😄 IMHO, the dark-themed editor (or even the dark mode) can be deferred until the beta is shipped, but if you would like that feature implemented, let me know if I could give you a hand.

**Comment by Bouncey** [comment]
It is a deal-breaker for me! I have already told @raisedadead off for merging it! :laughing:

**Comment by raisedadead** [comment]
Sooory. I promise we will get your editor back!

**Pull request merged**
