### PR TITLE
Use @freecodecamp/curriculum package

### LINKED ISSUE #84: jQuery code appears in the preview pane
Challenge Name(s)
jQuery - Target HTML Elements with Selectors Using jQuery 
https://learn.freecodecamp.org/front-end-libraries/jquery/target-html-elements-with-selectors-using-jquery
then each lesson in jQuery following this one .. 
it appears to be affecting the challenges as I can't pass any of them

Browser Information
Browser Name, Version:
Firefox Quantum 60.0.1 (64-bit)
Chrome: Version 66.0.3359.117 (64-bit)
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Dell Latitude Laptop (15")

Issue Description:
The jQuery code is appearing in the preview pane on the right hand side. This occurs as of the Target HTML Elements with Selectors Using jQuery. I have tested a majority of the lessons and the lessons don't pass. 

image

image

### PR DESCRIPTION
**Pull request by Bouncey**
Closes #84

### CODE REVIEW

**Comment by raisedadead** [comment]
Do you still need to make that schema change here? No right? Its to be done on the main repo? correct?

**Comment by mstellaluna** [comment]
I'll get on it asap

**Comment by mstellaluna** [comment]
@Bouncey  @raisedadead I'm still having the same issue with jquery lessons. I tried in FF to make sure I wasn't accessing a cached version of the jquery lessons

**Comment by raisedadead** [comment]
@mstellaluna you are checking on the deploy preview right? and not on learn app itself?

**Comment by mstellaluna** [comment]
@Bouncey  @raisedadead  looks great ! approving !

**Comment by raisedadead** [comment]
Hi @mstellaluna thanks for the QA. Yup we are currently restricting the merge rights on this to only Stuart, Quincy and myself. That's only because merging in a PR here deploys it to the production version.

We will soon enable a `staging` branch with the access to all issue mods. Once we have figured out the branch builds.

**Pull request merged**
