### PR TITLE
fix: night mode tweaks

### PR DESCRIPTION
**Pull request by thatnini**
A couple of tweaks to night mode

- Allows the ability to see the selection of text in the editor:
Before
text selection before
After
text selection after

- Make the test result odd rows darker:
Before
style multiple elements - before
After
style multiple elements - after

Fixes partially [freeCodeCamp/freeCodeCamp/#17782](https://github.com/freeCodeCamp/freeCodeCamp/issues/17782)

### CODE REVIEW

**Comment by huyenltnguyen** [comment]
@thatnini @Bouncey I feel super bad about what I'm going to say. I don't want to discard someone's contributions, but we can get the `vs-dark` theme to work and resolve the text selection issue in the process if we, um, remove all the night styles for the code editor. :(

Here is the result on my local copy:
untitled

**Comment by Bouncey** [comment]
@huyenltnguyen No need to feel bad, if that is the fix then that is great. Have those changes been pushed up to this branch?

**Comment by thatnini** [comment]
Don't feel bad, I just wasn't sure if we wanted to continue using the custom theme or vs-dark for the editor, so my original fix was just to remove the offending lines and leave the rest as is.

I've now removed what I believe to be the rest of the css that was used to create the custom dark theme for the editor.

**Comment by raisedadead** [comment]
> I've now removed what I believe to be the rest of the css that was used to create the custom dark theme for the editor.

Perfect. Thanks for making these changes. This LGTM

**Comment by Bouncey** [comment]
Thanks @huyenltnguyen and @thatnini :+1:

**Comment by huyenltnguyen** [comment]
Thanks @thatnini .

**Comment by renojvarghese** [comment]
Hey @huyenltnguyen @thatnini. I was the one who implemented the colors for the code editor. Don't feel bad. There were a lot of issues with my implementation. I understand why you had to take my styles out. It works better this way.

@Bouncey  @raisedadead. I am so sorry for all the issues I caused with night mode. I didn't qa my code as properly as I should have. It was one of my first open source contributions, and I was too eager to design the code editor. I'll stick to more of the beginner issues from now on to get a better understanding of the codebase.

**Comment by raisedadead** [comment]
@renojvarghese @thatnini @huyenltnguyen 

Do not worry, I would rather recommend on working on anything that you wish like. This is Git. Everything is detectable and reversible. So breaking things is encouraged and OKAY. This is the only way we can learn ensure good quality.

Thanks a lot for for working on the getting the night mode working. Keep up the good work.

Cheers and Happy Contributing.

**Pull request merged**
